import type { AppState, HistoryType } from "./types";

/**
 * In-flow test guide: one walkthrough per scenario.
 * Each step says what to click, what you should see, and which spec items it proves.
 * `check` auto-ticks the step from the live state; steps without a check are ticked by hand.
 */
export interface GuideStep {
  id: string;
  title: string;
  do: string;
  expect: string;
  href?: string;
  refs?: string[];
  /** Optional hint shown in amber, e.g. "Reset the scenario first". */
  note?: string;
  check?: (s: AppState, pathname: string) => boolean;
}

export interface Guide {
  scenarioId: string;
  goal: string;
  steps: GuideStep[];
}

const has = (s: AppState, t: HistoryType) => s.history.some((h) => h.type === t);
const sub = (s: AppState) => s.subscription;

export const GUIDES: Record<string, Guide> = {
  free: {
    scenarioId: "free",
    goal: "Prove the checkout: consent before pay, saved card, 3DS handling, and the first receipt.",
    steps: [
      {
        id: "free-1",
        title: "Open the plan page",
        do: "Click 'Upgrade plan' in the top bar (or Settings → Billing → Change plan).",
        expect: "Four plans with the Monthly / Yearly toggle. Free is marked 'Your current plan'. Plan facts match privyid.com/pricing (AUD).",
        href: "/plans",
        refs: ["UX-01", "UX-13"],
        check: (_s, p) => p.startsWith("/plans") || p.startsWith("/settings/billing/change-plan"),
      },
      {
        id: "free-paywall",
        title: "Hit the Free limit and see the paywall",
        do: "Home → 'Send an envelope' → pick a file (the drop zone) 4 times (4 sends left), then open it once more. Or use 'Use up envelope quota' in the Prototype panel.",
        expect: "The counter drops to '0 sends left' in red and 'Upgrade plan' appears. The upload screen now opens with the paywall on top: 'Your plan does not go this far', the reset date, Personal and Pro options, 'Not now' / 'Upgrade plan'. Picking a plan goes straight to checkout.",
        href: "/home",
        refs: ["M-17", "UX-27", "UX-28"],
        check: (s) => s.usage.envelopesSent >= 5,
      },
      {
        id: "free-2",
        title: "Subscribe to Personal Monthly with card 4242",
        do: "Upgrade to Personal → keep Monthly → card 4242 4242 4242 4242, any future expiry → tick the consent box → Pay.",
        expect: "Pay stays disabled until the unticked consent box is ticked. Toast confirms. Billing shows 'Renews on Oct 10, 2026 for A$7.49 on card ending 4242'. Email N-01 with invoice.",
        href: "/plans",
        refs: ["M-01", "R-12", "R-13", "N-01", "UX-06"],
        check: (s) => !!sub(s) && sub(s)!.tier === "personal" && has(s, "subscribed"),
      },
      {
        id: "free-3",
        title: "See the 3DS step",
        do: "Reset scenario (Prototype panel), subscribe again with 4000 0025 0000 3155.",
        expect: "A 'Your bank needs a quick confirmation' step appears before the charge completes; approving it finishes the checkout on the same screen.",
        href: "/plans",
        refs: ["M-07", "UX-14"],
        note: "Optional. Reset the scenario first.",
        check: (s) => s.card?.last4 === "3155" && has(s, "subscribed"),
      },
      {
        id: "free-4",
        title: "Compare Monthly vs Yearly",
        do: "Flip the toggle to Yearly on the plan page.",
        expect: "Personal A$6.58/mo billed A$79 (save 12%), Pro A$33/seat/mo billed A$396 (save 14%). The checkout lets you switch between the two as well.",
        href: "/plans",
        refs: ["UX-21"],
      },
      {
        id: "free-5",
        title: "Buy Pro and get a second workspace",
        do: "Reset scenario. Plans → Upgrade to Pro → 3 seats → name the workspace → card 4242 → consent → Pay.",
        expect: "You land in the new Pro workspace with a welcome step (M-15). Open the avatar menu: two workspaces. Switch to your Individual one: the plan reads 'Personal · included with Pro' with unlimited envelopes and no charge.",
        href: "/plans",
        refs: ["M-15", "R-73", "R-74", "R-76"],
        note: "Reset the scenario first.",
        check: (s) => has(s, "workspace_created"),
      },
    ],
  },

  "personal-monthly": {
    scenarioId: "personal-monthly",
    goal: "Prove the three plan changes from Personal Monthly: tier upgrade with a timing choice, interval switch with roll-over, cancel and resume.",
    steps: [
      {
        id: "pm-1",
        title: "Upgrade to Pro and read the timing choice",
        do: "Settings → Billing → Change plan → Upgrade to Pro.",
        expect: "Modal with two buttons: 'Upgrade now and pay A$38.50' and 'Upgrade on Oct 10, 2026 instead'. The acknowledgment sentence names the days forfeited. Pending downgrades/cancellations would be removed (stated in the modal).",
        href: "/settings/billing/change-plan",
        refs: ["M-02", "UX-03", "UX-05", "R-26", "R-27"],
        check: (s) => has(s, "upgraded") || sub(s)?.scheduledChange?.kind === "scheduled_upgrade",
      },
      {
        id: "pm-2",
        title: "Switch to Personal Yearly (roll-over)",
        do: "Reset scenario → Change plan → Yearly toggle → Personal → confirm.",
        expect: "A$79 charged today; the 30 remaining monthly days are appended, so the new end date is Oct 10, 2027. Billing anchor becomes today (the 10th). No forfeiture warning.",
        href: "/settings/billing/change-plan",
        refs: ["M-03", "R-28", "Rule B"],
        note: "Reset the scenario first if you did step 1.",
        check: (s) => has(s, "interval_changed"),
      },
      {
        id: "pm-3",
        title: "Cancel, then resume",
        do: "Billing → Cancel subscription → (skip the survey) → Cancel. Then click Resume in the banner.",
        expect: "Two clicks to cancel; access continues to Oct 10; email N-13. Resume is one click with a consent line; email N-15; same renewal date, nothing charged.",
        href: "/settings/billing",
        refs: ["M-05", "M-06", "UX-11", "UX-12", "R-33", "R-34"],
        check: (s) => has(s, "cancel_scheduled") && has(s, "resumed"),
      },
      {
        id: "pm-4",
        title: "Vouchers are for Free accounts only",
        do: "Plan page → 'Have a voucher code? Redeem it here' → AU-PERSONAL-3M → Claim. Then try AU-EARLY-1M (expired) and HELLO123.",
        expect: "'Voucher codes are only for accounts on the Free plan. You are on Personal Monthly.' A paid account sees this for anything it types, including wrong, expired or other-region codes. Nothing changes on the subscription and no quota is used.",
        href: "/plans",
        refs: ["V8", "M-20"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "NOT_FREE"),
      },
    ],
  },

  "personal-annual": {
    scenarioId: "personal-annual",
    goal: "The highest-risk matrix cell: upgrading now would forfeit 200 prepaid days. Prove the smart default, the acknowledgment and the scheduled path.",
    steps: [
      {
        id: "pa-1",
        title: "Open the upgrade modal and read it",
        do: "Change plan → Upgrade to Pro. Do not confirm yet.",
        expect: "Because 200 days remain (more than 14), 'Upgrade on Mar 29, 2027 instead' is the primary button and 'Upgrade now' is secondary. The checkbox reads '...paid until Mar 29, 2027 (200 days), will end today and is not refunded or credited'.",
        href: "/settings/billing/change-plan",
        refs: ["UX-04", "UX-05", "M-02"],
      },
      {
        id: "pa-2",
        title: "Choose the scheduled upgrade",
        do: "Click 'Upgrade on Mar 29, 2027 instead'.",
        expect: "Nothing charged. Banner 'Your plan changes to Pro on Mar 29, 2027. Keep my current plan'. Email N-11. Billing page shows the pending change.",
        refs: ["R-27", "UX-09", "B-02", "N-11"],
        check: (s) => sub(s)?.scheduledChange?.kind === "scheduled_upgrade",
      },
      {
        id: "pa-3",
        title: "Undo it from the banner",
        do: "Click 'Keep my current plan'.",
        expect: "Pending change removed, toast confirms, history shows 'change undone'.",
        refs: ["UX-09", "R-30"],
        check: (s) => has(s, "change_undone"),
      },
      {
        id: "pa-4",
        title: "Downgrade to Personal Monthly",
        do: "Change plan → Monthly toggle → Personal (Get Personal monthly).",
        expect: "Light confirmation: 'From Mar 29, 2027 you pay A$7.49 per month'. Effective at the end of the annual term, anchor unchanged, undo available until then.",
        href: "/settings/billing/change-plan",
        refs: ["M-04b", "R-32", "Rule D"],
        check: (s) => ["downgrade", "interval_down"].includes(sub(s)?.scheduledChange?.kind ?? "") && sub(s)?.scheduledChange?.interval === "monthly",
      },
    ],
  },

  "business-owner": {
    scenarioId: "business-owner",
    goal: "Prove the two-workspace model for an owner (perk in Individual, team in Pro), then seats prorated to the one renewal date, backup cards, and the downgrade checklist.",
    steps: [
      {
        id: "bo-ws-1",
        title: "Switch between your workspaces",
        do: "Avatar menu (top right) → 'Frans · Individual'. Look at the plan chip on Home and Settings → Billing. Then switch back to 'Privy Product Team'.",
        expect: "Individual shows 'Personal · included with Pro' with unlimited envelopes and a billing card that points to the Pro workspace. Pro shows 'Pro · active' with seats, members, invoices.",
        href: "/home",
        refs: ["R-73", "R-76", "R-77"],
        check: (s) => s.activeWorkspace === "individual",
      },
      {
        id: "bo-ws-2",
        title: "Invite a member into a free seat",
        do: "Pro workspace → Billing → Team members → Invite member → any email → Send.",
        expect: "6 of 8 seats were used, so the invite works without buying seats. The list grows to 7; the invitee's own plan is untouched (R-71). Try again after all 8 seats are used: the button explains you need more seats.",
        href: "/settings/billing",
        refs: ["R-78", "R-71"],
        check: (s) => has(s, "member_invited"),
      },
      {
        id: "bo-ws-2b",
        title: "Make an admin, and move envelopes into the Pro workspace",
        do: "Team members → 'Make admin' next to Rima. Then switch to Individual → Envelopes → select → 'Hand over' → Privy Product Team.",
        expect: "Rima's chip turns to Admin (admins manage members, seats and cards; only you change the plan, transfer, set admins, delete). The envelopes appear in the Pro workspace list.",
        href: "/settings/billing",
        refs: ["R-82", "R-79"],
        check: (s) => has(s, "role_changed"),
      },
      {
        id: "bo-ws-3",
        title: "Invite when every seat is taken: seat added in the same flow",
        do: "Invite two more members so 8 of 8 seats are used, then click 'Invite member (+1 seat)' again → email → tick the consent → 'Add seat, pay A$26.95 and invite'.",
        expect: "One modal does both: prorated charge for 1 seat (21 of 30 days, same Oct 1 renewal), then the invitation. Seats become 9, invoice and email N-22 for the seat, history shows both.",
        href: "/settings/billing",
        refs: ["UX-29", "M-09", "R-12"],
        check: (s) => (s.subscription?.seats ?? 0) >= 9 && has(s, "member_invited"),
      },
      {
        id: "bo-ws-4",
        title: "Transfer ownership to a member",
        do: "Team members → 'Make owner' next to Kenny Hartono → read the billing consequences → tick → Transfer.",
        expect: "Your card is detached (subscription ended, no further charges). The workspace moves to 'Other workspaces' with Kenny as owner and banner B-10 'has not set up payment yet' until Oct 1. Your Individual workspace is back to Free. Emails N-35 (to Kenny) and N-36 (to you).",
        refs: ["M-18", "R-81", "N-35", "N-36", "B-10"],
        note: "Do this last, or reset afterwards: the other steps need you to be the owner.",
        check: (s) => has(s, "ownership_transferred"),
      },
      {
        id: "bo-seats-1",
        title: "Add 2 seats, prorated to the same end date",
        do: "Billing → Manage seats → set 10 → read the breakdown → tick the consent → 'Add 2 seats and pay'.",
        expect: "Today: 2 × A$38.50 × 21 of 30 days = A$53.90 (A$26.95 per seat). Next renewal Oct 1 stays the same date, now A$385.00 for 10 seats. Invoice for the prorated amount, email N-22, history entry.",
        href: "/settings/billing",
        refs: ["M-09", "UX-06", "N-22", "Rule B"],
        check: (s) => s.history.some((h) => h.type === "seats_changed" && h.title.startsWith("Added")),
      },
      {
        id: "bo-seats-2",
        title: "Reduce seats: takes effect at the renewal date",
        do: "Manage seats → set 7 → 'Reduce to 7 on Oct 1, 2026'. Try 5 as well: blocked because 6 members are using seats.",
        expect: "Nothing charged or refunded now; banner 'Your seats change from 10 to 7 on Oct 1' with 'Keep my seats'. Renewal shows the new amount. Jumping to Oct 1 applies it and the history shows 'Seats reduced to 7'.",
        href: "/settings/billing",
        refs: ["M-09", "Rule D", "B-02", "UX-09"],
        check: (s) => s.subscription?.pendingSeats != null || s.history.some((h) => h.type === "seats_changed" && h.title.startsWith("Seats reduced")),
      },
      {
        id: "bo-cards-1",
        title: "See the backup card catch a declined default",
        do: "Prototype panel → 'Next automatic charge outcome' → Soft decline. Then in this panel 'Jump to next renewal (Oct 1)'.",
        expect: "The Visa default declines, the Mastercard backup is charged in the same sweep. No grace period, no dunning email. History: 'Backup card ending 4444 was charged'. Email N-23 explains which card was used.",
        refs: ["R-19b", "N-23"],
        check: (s) => s.history.some((h) => h.type === "note" && h.title.includes("Backup card")),
      },
      {
        id: "bo-cards-2",
        title: "Manage cards: set default, add, remove",
        do: "Billing → Payment methods → Manage. Set the Mastercard as default, add a backup card (5555 5555 5555 4444 or 4242), remove a backup.",
        expect: "Default is charged first; backups listed in order; 'Remove' on the only card of an active subscription is disabled; removing the default promotes the first backup. N-21 / N-24 emails.",
        href: "/settings/billing/payment-method",
        refs: ["UX-17", "N-21", "N-24"],
        check: (s) => s.history.some((h) => h.type === "card_removed" || (h.type === "card_updated" && h.title.includes("changed"))),
      },
      {
        id: "bo-1",
        title: "Downgrade to Personal and read the checklist",
        do: "Change plan → Personal (Get Personal).",
        expect: "Checklist lists the 5 members by name (Kenny, Rima, Fauzi, Donny, Ardhitia), 3 automations, 2 retention policies, e-Seal, branding and trusted domain privy.id, envelopes to 50/month. 'Hand over team documents' link. Effective Oct 1, 2026. Seat changes are blocked while a plan change is pending.",
        href: "/settings/billing/change-plan",
        refs: ["M-04", "UX-07", "UX-08", "R-31"],
        check: (s) => sub(s)?.scheduledChange?.kind === "downgrade",
      },
      {
        id: "bo-2",
        title: "Undo from the banner",
        do: "Click 'Keep my current plan' in the banner.",
        expect: "Pending change removed; members untouched.",
        refs: ["UX-09"],
        check: (s) => has(s, "change_undone"),
      },
      {
        id: "bo-3",
        title: "Schedule again and jump to Oct 1",
        do: "Repeat step 1, then in this panel click 'Jump to scheduled change'.",
        expect: "A$7.49 charged for Personal Monthly. Privy Product Team becomes read-only (view and download only) for you and the 5 members, and stays in the switcher marked Expired. Emails N-12 to Frans and N-16 to each member.",
        refs: ["R-31", "N-12", "N-16", "R-36"],
        check: (s) => has(s, "change_applied"),
      },
    ],
  },

  "past-due": {
    scenarioId: "past-due",
    goal: "Prove dunning: the grace banner, the email series, recovery with unchanged billing date, and the Day-14 drop to Free.",
    steps: [
      {
        id: "pd-1",
        title: "Read the past-due banner",
        do: "Look at the top of any page.",
        expect: "'We could not renew your Personal Monthly. You have 7 days of full access left.' with 'Update payment method'. Everything still works (full access during grace).",
        href: "/home",
        refs: ["B-01", "UX-16", "R-22"],
      },
      {
        id: "pd-2",
        title: "Open the emails sent so far",
        do: "Prototype panel → Emails (or the link below).",
        expect: "N-05 (Day 0, payment failed, retry dates) and N-07 (Day 7 reminder), both with a one-click 'Update payment method' link.",
        href: "/prototype/emails",
        refs: ["N-05", "N-07", "UX-18"],
        check: (_s, p) => p.startsWith("/prototype/emails"),
      },
      {
        id: "pd-3",
        title: "Recover by replacing the card",
        do: "Billing → Payment method → Replace card with 4242.",
        expect: "Immediate retry succeeds; status back to active; renewal date stays Oct 3, 2026 (anchor unchanged); banner gone; receipt N-03; toast 'Payment received'.",
        href: "/settings/billing/payment-method",
        refs: ["R-22", "R-25", "R-37", "UX-17", "N-03"],
        check: (s) => has(s, "recovered"),
      },
      {
        id: "pd-3b",
        title: "Alternative: add a backup card instead",
        do: "Reset scenario → Billing → Payment methods → Manage → Add backup card 4242 (leave 'Make default' unticked).",
        expect: "Saving any card during grace retries right away: the Visa 9995 is declined again, the new backup succeeds, plan recovers with the same billing date. Email N-23 explains the backup was used; N-24 confirms the card was added.",
        href: "/settings/billing/payment-method",
        refs: ["R-19b", "R-22", "N-23", "N-24"],
        note: "Reset the scenario first.",
        check: (s) => (s.backupCards ?? []).length > 0 && has(s, "recovered"),
      },
      {
        id: "pd-4",
        title: "Alternative: let grace run out",
        do: "Reset scenario, then click 'Jump to end of grace' in this panel.",
        expect: "Day 12: N-08 final warning; Day 14: last retry fails, account drops to Free, documents intact, open invoice voided, email N-09, banner replaced by 'Resubscribe'.",
        refs: ["R-23", "N-08", "N-09"],
        note: "Reset the scenario first.",
        check: (s) => has(s, "ended"),
      },
    ],
  },

  "pending-downgrade": {
    scenarioId: "pending-downgrade",
    goal: "A scheduled change waiting to happen: prove undo, the effective-date job, and that an upgrade replaces the pending change.",
    steps: [
      {
        id: "pdg-1",
        title: "Undo from the banner",
        do: "Click 'Keep my current plan'.",
        expect: "Pending change cleared; Pro Monthly × 3 continues; history 'change undone'.",
        refs: ["UX-09", "R-30"],
        check: (s) => has(s, "change_undone"),
      },
      {
        id: "pdg-2",
        title: "Let it take effect",
        do: "Reset scenario → 'Jump to scheduled change' (Oct 1).",
        expect: "Personal Monthly charged A$7.49, the 2 other members removed, workspace closed, N-12 to Frans and N-16 to Kenny and Rima.",
        refs: ["R-31", "N-12", "N-16"],
        note: "Reset the scenario first.",
        check: (s) => has(s, "change_applied"),
      },
      {
        id: "pdg-3",
        title: "Upgrade instead",
        do: "Reset scenario → Change plan → Yearly → Pro → Upgrade now.",
        expect: "Modal states the pending downgrade will be removed. After paying, no scheduled change remains; Pro Yearly runs from today.",
        href: "/settings/billing/change-plan",
        refs: ["R-29", "M-02"],
        note: "Reset the scenario first.",
        check: (s) => has(s, "upgraded") || has(s, "interval_changed"),
      },
    ],
  },

  "cancel-scheduled": {
    scenarioId: "cancel-scheduled",
    goal: "Cancelled but still paid: prove one-click resume, the clean end of the period, and that resubscribing starts a fresh billing date.",
    steps: [
      {
        id: "cs-1",
        title: "Resume from the banner",
        do: "Click 'Resume' in the banner.",
        expect: "Consent line for the recurring charge, then auto-renewal is back on: next renewal Oct 15, 2026 for A$79. Email N-15. Nothing charged now.",
        refs: ["M-06", "UX-12", "R-34", "N-15"],
        check: (s) => has(s, "resumed"),
      },
      {
        id: "cs-2",
        title: "Let the plan end",
        do: "Reset scenario → 'Jump to plan end' (Oct 15).",
        expect: "Account on Free, documents intact, no charge attempted, email N-14.",
        refs: ["R-33", "N-14"],
        note: "Reset the scenario first.",
        check: (s) => has(s, "ended"),
      },
      {
        id: "cs-3",
        title: "Resubscribe after the lapse",
        do: "Upgrade plan → Personal Monthly → card 4242.",
        expect: "A new subscription with billing anchor = today's simulated date (not the old 15th).",
        href: "/plans",
        refs: ["R-25"],
        check: (s) => has(s, "ended") && s.history[0]?.type === "subscribed",
      },
    ],
  },

  "migrated-prepaid": {
    scenarioId: "migrated-prepaid",
    goal: "Old one-off buyer with stacked prepaid time: prove we never auto-enrol, opt-in charges nothing, and upgrades are scheduled only.",
    steps: [
      {
        id: "mp-1",
        title: "Turn on auto-renewal from the banner",
        do: "Click 'Turn on auto-renewal' → card 4242 → tick consent → Save.",
        expect: "No charge today. A subscription is created whose first charge is Nov 10, 2027 (end of prepaid time). Consent stored. Banner gone.",
        refs: ["B-03", "UX-24", "R-42", "Q-J1"],
        check: (s) => has(s, "opt_in"),
      },
      {
        id: "mp-2",
        title: "Try to upgrade to Pro",
        do: "Change plan → Upgrade to Pro.",
        expect: "Only 'Upgrade on Nov 10, 2027' is offered in self-serve (more than one prepaid period: no immediate forfeiture path). Credit is a CS action.",
        href: "/settings/billing/change-plan",
        refs: ["R-43", "Q-D7"],
        check: (s) => sub(s)?.scheduledChange?.kind === "scheduled_upgrade",
      },
      {
        id: "mp-3",
        title: "Jump to the end of prepaid time",
        do: "Click 'Jump to end of prepaid time' in this panel (reminders N-04 fire at T-30 and T-7 on the way).",
        expect: "First automatic charge on Nov 10, 2027; receipt N-03; entitlement continues with no gap.",
        refs: ["R-16", "R-17", "N-04"],
        check: (s) => has(s, "renewed"),
      },
    ],
  },

  "business-member-free": {
    scenarioId: "business-member-free",
    goal: "Membership never upgrades your own plan: Free stays Free with 5 envelopes, while the owner's workspace is unlimited.",
    steps: [
      {
        id: "bmf-1",
        title: "Compare the two workspaces",
        do: "Home shows 'Frans · Individual · Free' (4 sends left). Avatar menu → 'Hartono Legal Partners'.",
        expect: "Kenny's Pro workspace: unlimited envelopes, its own task list, no Upgrade button in the top bar. Billing says 'managed by Kenny Hartono' with no actions.",
        href: "/home",
        refs: ["R-71", "R-76"],
        check: (s) => s.activeWorkspace === "ws_kenny",
      },
      {
        id: "bmf-2",
        title: "Plans page inside a member workspace",
        do: "In Kenny's workspace open Upgrade plan (or Settings → Billing → Change plan).",
        expect: "No plan cards: 'Plans are chosen per workspace' with a button back to your Individual workspace.",
        href: "/plans",
        refs: ["R-71"],
        check: (s, p) => s.activeWorkspace === "ws_kenny" && p.startsWith("/plans"),
      },
      {
        id: "bmf-leave",
        title: "Leave Kenny's workspace",
        do: "In Hartono Legal Partners: avatar menu → 'Leave this workspace' (or Billing → Leave workspace) → tick the acknowledgment → Leave.",
        expect: "You land in your Individual workspace; Kenny's workspace is gone from the switcher. The modal explained that your documents there stay with the owner. Your Free plan is untouched.",
        refs: ["M-16", "R-80"],
        note: "Optional. Reset the scenario afterwards if you want Kenny's workspace back for step 3.",
        check: (s) => has(s, "workspace_left"),
      },
      {
        id: "bmf-3",
        title: "Buy your own Pro plan",
        do: "Switch to Individual → Upgrade plan → Upgrade to Pro → 2 seats → name it → card 4242 → Pay.",
        expect: "A third workspace appears: yours. Your Individual workspace becomes 'Personal · included with Pro' (unlimited). Kenny's workspace is unchanged.",
        href: "/plans",
        refs: ["R-70", "R-73", "R-74", "M-15"],
        check: (s) => has(s, "workspace_created"),
      },
    ],
  },
  "business-member-personal": {
    scenarioId: "business-member-personal",
    goal: "A paying Personal subscriber who is also a member: the 50-envelope limit stays until they buy Pro themselves.",
    steps: [
      {
        id: "bmp-1",
        title: "Check the limit in the Individual workspace",
        do: "Home / Billing in 'Frans · Individual'.",
        expect: "Personal Monthly, 47 of 50 envelopes used, 3 sends left. Membership of Kenny's Pro and PT Privy (Demo) Enterprise does not lift this.",
        href: "/settings/billing",
        refs: ["R-71"],
        check: (_s, p) => p === "/settings/billing",
      },
      {
        id: "bmp-paywall",
        title: "Use the last 3 envelopes",
        do: "Home → 'Send an envelope' → pick a file, three times; then open it once more.",
        expect: "'0 sends left' in red, 'Upgrade plan' appears, and the upload screen shows the paywall with only Pro offered (you already have Personal) and the reset date Oct 10.",
        href: "/home",
        refs: ["M-17", "UX-28"],
        check: (s) => s.usage.envelopesSent >= 50,
      },
      {
        id: "bmp-ending",
        title: "Owner cancelled: members are warned; you are an admin there",
        do: "Avatar menu → Hartono Legal Partners → Billing.",
        expect: "Banner B-10: Kenny's plan ends on Oct 1, 2026 and the workspace becomes read-only then. Billing shows 'You are an admin': you can invite and remove members (5 of 6 seats), but the plan, seats and cards stay with Kenny.",
        refs: ["B-10", "R-82"],
        check: (s) => s.activeWorkspace === "ws_kenny",
      },
      {
        id: "bmp-handover",
        title: "Take your own envelope with you",
        do: "Envelopes in Kenny's workspace → only 'Consultation notes' can be ticked (you uploaded it) → Hand over → Frans (Individual).",
        expect: "It moves to your Individual workspace; Kenny's envelopes cannot be selected.",
        refs: ["R-79"],
        check: (s) => has(s, "handover"),
      },
      {
        id: "bmp-2",
        title: "Look at the Enterprise workspace",
        do: "Avatar menu → PT Privy (Demo).",
        expect: "Enterprise · active, contract until Mar 31, 2027, 'Contact sales', no self-serve plan. Unlimited envelopes there.",
        refs: ["R-71"],
        check: (s) => s.activeWorkspace === "ws_ent_demo",
      },
      {
        id: "bmp-3",
        title: "Upgrade Personal to Pro (rule C still applies)",
        do: "Individual → Change plan → Upgrade to Pro → choose 'Upgrade now' → acknowledge the forfeited Personal days → name the workspace → Pay.",
        expect: "Personal ends today (no credit), Pro starts with a new billing date, your own Pro workspace is created and Individual becomes 'included with Pro'.",
        href: "/settings/billing/change-plan",
        refs: ["Rule C", "UX-03", "R-74"],
        check: (s) => has(s, "workspace_created"),
      },
    ],
  },
  "business-expired": {
    scenarioId: "business-expired",
    goal: "An expired Pro workspace is read-only, not gone: prove view/download only, the handover to Individual, and reactivation.",
    steps: [
      {
        id: "bx-1",
        title: "Read-only workspace",
        do: "Home and Envelopes in 'Privy Product Team'.",
        expect: "Banner B-09 'read-only since Sep 1, 2026'. Send an envelope and Sign are disabled; Download works. Top bar says 'Reactivate plan'. The switcher marks the workspace Expired.",
        href: "/envelopes",
        refs: ["R-72", "B-09"],
        check: (_s, p) => p === "/envelopes",
      },
      {
        id: "bx-2",
        title: "Individual is back to Free",
        do: "Avatar menu → 'Frans · Individual'.",
        expect: "Plan chip 'Free', 5 envelopes a month. The owner perk ended with the Pro plan.",
        refs: ["R-73"],
        check: (s) => s.activeWorkspace === "individual",
      },
      {
        id: "bx-3",
        title: "Hand envelopes over, to you or to each uploader",
        do: "Privy Product Team → Envelopes → select all → 'Hand over 4' → choose 'Frans (Individual)' or 'Each uploader's Individual workspace' → confirm.",
        expect: "To you: all 4 land in your Individual workspace. To each uploader: Kenny's and Rima's go to them, yours to you. The Pro workspace is left empty with the handover date.",
        refs: ["R-79", "UX-08"],
        check: (s) => has(s, "handover"),
      },
      {
        id: "bx-3b",
        title: "Delete the workspace",
        do: "Billing → 'Delete workspace' → keep 'Move envelopes to my Individual workspace' ticked → type the name → Delete.",
        expect: "The workspace disappears from the switcher. The plan page offers 'Upgrade to Pro' again, which would create a brand-new workspace.",
        refs: ["M-19", "R-83"],
        note: "Optional. Reset the scenario before step 4.",
        check: (s) => has(s, "workspace_deleted"),
      },
      {
        id: "bx-4",
        title: "Reactivate Pro",
        do: "Billing → 'Reactivate Pro' → 4 seats → card 4242 → consent → Pay.",
        expect: "New subscription from today (new billing date), workspace active again, members can sign, Individual returns to 'included with Pro'.",
        href: "/settings/billing",
        refs: ["R-75"],
        check: (s) => has(s, "workspace_reactivated"),
      },
    ],
  },
  "enterprise-member": {
    scenarioId: "enterprise-member",
    goal: "The production switcher: Individual plus Enterprise workspaces, one of them expired. Enterprise has no self-serve billing.",
    steps: [
      {
        id: "em-1",
        title: "Open the switcher",
        do: "Avatar menu.",
        expect: "Current: Frans · Individual. Others: PT Privy (Demo) · Enterprise, PT Privy Demo May 2026 · Enterprise · Expired. Settings, Help centre, Log out below.",
        href: "/home",
        refs: ["R-76"],
      },
      {
        id: "em-2",
        title: "Expired Enterprise workspace",
        do: "Switch to PT Privy Demo May 2026 → Envelopes.",
        expect: "Read-only banner with a contact-sales note; Download works, nothing else. Billing shows the contract ended Aug 31, 2026.",
        refs: ["R-72"],
        check: (s) => s.activeWorkspace === "ws_ent_may",
      },
      {
        id: "em-3",
        title: "Your own plan is still yours",
        do: "Switch to Individual → Upgrade plan.",
        expect: "Free with the normal plan cards. Buying Personal or Pro here never touches the Enterprise workspaces.",
        href: "/plans",
        refs: ["R-71"],
        check: (s, p) => s.activeWorkspace === "individual" && p.startsWith("/plans"),
      },
    ],
  },
  "voucher-free": {
    scenarioId: "voucher-free",
    goal: "Claim a voucher end to end: free plan with no card, one benefit at a time, the two ways to buy during the free period, and the automatic return to Free.",
    steps: [
      {
        id: "vf-1",
        title: "Open the voucher window",
        do: "Plan page → 'Have a voucher code? Redeem it here'. Billing also has 'Redeem a voucher code' while you are on Free.",
        expect: "Window 'Voucher code' with one field and the 'Claim' button, same layout as production. Claim stays disabled until you type something.",
        href: "/plans",
        refs: ["M-20"],
        check: (_s, p) => p.startsWith("/plans"),
      },
      {
        id: "vf-2",
        title: "Claim AU-PERSONAL-3M",
        do: "Type 'au personal 3m' (lower case, spaces instead of dashes) → Claim.",
        expect: "Case, spaces and dashes are ignored. Success: 'Personal is yours for 3 months', free until Dec 10, 2026 (3 calendar months). No card asked. Prototype panel → Voucher codes shows 213 of 300 used.",
        refs: ["V1", "V4", "V12", "N-40"],
        check: (s) => s.prepaid?.source === "redeem",
      },
      {
        id: "vf-3",
        title: "Check Billing during the free period",
        do: "Settings → Billing.",
        expect: "Plan card: 'Free until Dec 10, 2026 · 91 days left', the voucher code, 'nothing will be charged'. No card, no bill, no invoice. The top bar counter now uses the Personal quota of 50 a month. Email N-40 in the Prototype panel → Emails.",
        href: "/settings/billing",
        refs: ["V12", "N-40"],
        check: (s, p) => s.prepaid?.source === "redeem" && p === "/settings/billing",
      },
      {
        id: "vf-4",
        title: "Claim again: same code, then a second code",
        do: "Plan page → Redeem it here → AU-PERSONAL-3M again. Then try 7K2M9XQ4HT.",
        expect: "Same code: 'Already claimed', same end date, quota still 213 (no double grant). Second code: 'You already have a free plan from a voucher until Dec 10, 2026. Vouchers can't be combined.' The same message appears for anything else typed, even a wrong code.",
        href: "/plans",
        refs: ["V7", "V9"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "ACTIVE_BENEFIT"),
      },
      {
        id: "vf-5",
        title: "Buy during the free period: start when it ends",
        do: "Billing → 'Keep Personal after Dec 10, 2026' (or pick any plan on the plan page) → 'Start on Dec 10, 2026' → card 4242 → tick consent → confirm.",
        expect: "A side by side choice first: 'When my free period ends' (recommended, nothing charged today) or 'Today'. After confirming: Billing shows 'Free until Dec 10, 2026 · then paid' and 'First charge on Dec 10, 2026'. No invoice yet.",
        href: "/settings/billing",
        refs: ["M-21", "R-12"],
        check: (s) => !!s.subscription?.promo,
      },
      {
        id: "vf-6",
        title: "Reach the end date: first charge",
        do: "Prototype panel → 'Jump to next renewal (Dec 10, 2026)'.",
        expect: "The first charge of A$7.49 happens on Dec 10 and the plan continues as a normal subscription with a receipt.",
        refs: ["R-01"],
        check: (s) => !!s.subscription && s.invoices.some((i) => i.status === "paid"),
      },
      {
        id: "vf-7",
        title: "Other paths (reset first)",
        do: "Reset the scenario and claim again. Path A: pick a plan → 'Start today and pay'. Path B: buy nothing and 'Jump to end of free period'.",
        expect: "Path A: charged today, the remaining free days end and are not credited (stated before you pay). Path B: the account returns to Free on Dec 10 with no payment attempt, banner 'Your free period has ended', email N-41, documents kept.",
        note: "Optional. Reset the scenario first.",
        refs: ["V12", "B-11", "N-41"],
      },
    ],
  },
  "voucher-rejections": {
    scenarioId: "voucher-rejections",
    goal: "See every rejection message and the limits behind it. Keep the Prototype panel open: its 'Voucher codes' section has the codes, the network switch, the clock, the next-claim response and the audit log.",
    steps: [
      {
        id: "vr-1",
        title: "Unknown code and paused code look the same",
        do: "Plan page → Redeem it here. Try HELLO123, then AU-PARTNER-3M (a real code that is paused).",
        expect: "Both give 'This code can't be used. Check the code and try again.' A guesser cannot tell a real paused code from a wrong one. The audit log records UNKNOWN and PAUSED separately.",
        href: "/plans",
        refs: ["V3", "V13"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "PAUSED") && !!s.vouchers?.audit.some((a) => a.reason === "UNKNOWN" && a.accountId === "acc_frans"),
      },
      {
        id: "vr-2",
        title: "Expired code and wrong region",
        do: "Try AU-EARLY-1M, then ID-PERSONAL-1M.",
        expect: "'This code expired on Aug 31, 2026.' and 'This code isn't available in your region (Australia).' The region is the one in Settings → Workspace preferences.",
        refs: ["V2", "V6"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "EXPIRED") && !!s.vouchers?.audit.some((a) => a.reason === "REGION"),
      },
      {
        id: "vr-3",
        title: "Email must be verified",
        do: "Try W9D5R7B4NK. In the verify step enter 000000, then 999999, then click 'Resend code', then enter any other 6 digits → 'Verify and claim'.",
        expect: "The window switches to 'Verify your email first'; the voucher is not used up and this does not count as a failed attempt. 000000: 'That code is incorrect…'. 999999: 'That code has expired. Request a new one.' Resend: 'We sent a new code to …' (the 4th resend says 'You have requested too many codes…'). After verifying, the same claim continues by itself.",
        refs: ["V18"],
        check: (s) => s.user.emailVerified !== false,
      },
      {
        id: "vr-4",
        title: "No quota left, then the 5-attempt lock",
        do: "The continued claim is rejected: W9D5R7B4NK is a unique code someone already used. Press Claim once more.",
        expect: "First: 'This code is no longer available. Its quota has been fully claimed.' That was the 5th failure in 15 minutes, so the next attempt says 'Too many attempts. Try again in 15 minutes.' Even a correct code is refused while locked.",
        refs: ["V1", "V11"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "RATE_LIMIT_ACCOUNT"),
      },
      {
        id: "vr-5",
        title: "Wait out the lock, then the per-network limit",
        do: "Prototype panel → '+15 min'. Set Network to Office. Try AU-PERSONAL-3M.",
        expect: "'This code can't be claimed from your network right now. Try again later or contact support.' Five accounts already claimed this promotion from the office network in the last 24 hours.",
        refs: ["V20"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "IP_LIMIT"),
      },
      {
        id: "vr-6",
        title: "The last-slot test",
        do: "Set Network back to Home. Prototype panel → AU-PERSONAL-3M → '50 claims on last slot', then try AU-PERSONAL-3M.",
        expect: "'This code is no longer available. Its quota has been fully claimed.' The audit log shows 50 parallel claims on the last slot: exactly 1 success and 49 rejections, quota 300 of 300.",
        refs: ["V1"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "EXHAUSTED" && a.accountId.startsWith("acc_load")),
      },
      {
        id: "vr-7",
        title: "Connection error and expired session",
        do: "Prototype panel → 'Next claim response' → Connection error, then try 7K2M9XQ4HT. Repeat with Session expired.",
        expect: "'We couldn't check your code, and your voucher was not used. Check your connection and try again.' and 'Your session has expired. Sign in again to claim your code.' Nothing is recorded, no quota is used and neither counts as a failed attempt.",
        refs: ["M-20"],
      },
      {
        id: "vr-8",
        title: "A valid claim still works: Pro code",
        do: "Try 7K2M9XQ4HT again.",
        expect: "'Pro is yours for 3 months'. A Pro workspace is created with 1 seat; the avatar menu now lists it. Quota is used only now, after every other check passed.",
        refs: ["V1", "V4", "V15"],
        check: (s) => s.prepaid?.source === "redeem" && s.prepaid.tier === "business",
      },
      {
        id: "vr-9",
        title: "Network lock and the audit log",
        do: "Reset the scenario. Prototype panel → '20 wrong guesses from this IP', then try any code. Open 'Audit log', filter by campaign and Export CSV.",
        expect: "'Too many attempts from your network. Try again in 60 minutes.' (switching Network lifts it, the lock belongs to that IP). The log lists every attempt with time, account, code, region, IP, result and reason, and exports to CSV.",
        href: "/prototype/voucher-log",
        refs: ["V22", "V19"],
        check: (s, p) => p.startsWith("/prototype/voucher-log"),
      },
      {
        id: "vr-10",
        title: "Pause a leaked code",
        do: "Reset the scenario. Prototype panel → Voucher codes → click 'Active' next to B8R3NW6YD5 so it reads 'Paused'. Try to claim it.",
        expect: "The generic 'This code can't be used' message at once, with no deploy. Accounts that already claimed keep their benefit. Click 'Paused' to resume.",
        note: "Optional. Reset the scenario first.",
        refs: ["V3"],
      },
    ],
  },
  "voucher-active": {
    scenarioId: "voucher-active",
    goal: "What a user on a free voucher period sees, and what happens on the end date when they do nothing.",
    steps: [
      {
        id: "va-1",
        title: "Billing during the free period",
        do: "Settings → Billing.",
        expect: "'Personal' with 'Free until Sep 16, 2026 · 6 days left', the voucher code and 'nothing will be charged'. Payment methods are empty and there is no bill. No renewal reminder banner.",
        href: "/settings/billing",
        refs: ["V12"],
        check: (_s, p) => p === "/settings/billing",
      },
      {
        id: "va-2",
        title: "Plan page during the free period",
        do: "Billing → Change plan.",
        expect: "Personal shows 'Free again on Sep 16, 2026' with 'Keep Personal'; Pro shows 'Switch to Pro'. Both open the choice between starting on Sep 16 or today.",
        href: "/settings/billing/change-plan",
        refs: ["M-21"],
        check: (_s, p) => p.startsWith("/settings/billing/change-plan") || p.startsWith("/plans"),
      },
      {
        id: "va-3",
        title: "Let the free period end",
        do: "Prototype panel → 'Jump to end of free period (Sep 16, 2026)'.",
        expect: "The account is on Free. No charge, no invoice, no grace period. Banner 'Your free period has ended', email N-41, and Subscription history says nothing was charged. Envelopes are kept; the counter is back to 5 a month.",
        refs: ["V12", "B-11", "N-41"],
        check: (s) => has(s, "promo_ended"),
      },
      {
        id: "va-4",
        title: "The same promotion cannot be claimed twice",
        do: "Billing → 'Redeem a voucher code' → AU-PERSONAL-3M. Then try 7K2M9XQ4HT (same promotion, different code).",
        expect: "Both: 'You have already claimed a code from this promotion.' One account, one claim per campaign, even after the first benefit ended.",
        href: "/settings/billing",
        refs: ["V7"],
        check: (s) => !!s.vouchers?.audit.some((a) => a.reason === "ALREADY_IN_CAMPAIGN"),
      },
    ],
  },
  "voucher-pro": {
    scenarioId: "voucher-pro",
    goal: "A Pro voucher: the workspace it creates, the 1-seat limit, and read-only at the end date unless Pro is bought.",
    steps: [
      {
        id: "vp-1",
        title: "The Pro workspace from a voucher",
        do: "Open the avatar menu, then Settings → Billing.",
        expect: "Workspace 'Frans's team' (Pro, owner) and Individual, both with unlimited envelopes. Billing: 'Pro' with 'Free until Nov 1, 2026', voucher 7K2M9XQ4HT, no card.",
        href: "/settings/billing",
        refs: ["V4", "V12"],
        check: (_s, p) => p === "/settings/billing",
      },
      {
        id: "vp-2",
        title: "Seats during the free period",
        do: "Billing → Team members → Invite member.",
        expect: "The free period includes 1 seat (the owner). The invite explains that seats can be added after subscribing to Pro; there is no 'Manage seats' button and nothing can be charged.",
        href: "/settings/billing",
        refs: ["V4"],
      },
      {
        id: "vp-3",
        title: "Let the free period end",
        do: "Prototype panel → 'Jump to end of free period (Nov 1, 2026)'.",
        expect: "'Frans's team' becomes read-only (view, download, hand over), the Individual workspace returns to Free, nothing is charged. Banner and email N-41 explain it; 'Reactivate Pro' is offered.",
        refs: ["V12", "R-72", "N-41"],
        check: (s) => has(s, "promo_ended"),
      },
      {
        id: "vp-4",
        title: "Keep Pro instead (reset first)",
        do: "Reset. Billing → 'Keep Pro after Nov 1, 2026' → choose seats → 'Start on Nov 1, 2026' → card 4242 → consent.",
        expect: "Nothing charged today. Billing shows 'Free until Nov 1, 2026 · then paid' and the first charge date. Jump to it: the charge is made and the workspace stays active.",
        note: "Optional. Reset the scenario first.",
        refs: ["M-21", "R-12"],
        check: (s) => !!s.subscription?.promo,
      },
    ],
  },
  "id-free": {
    scenarioId: "id-free",
    goal: "Indonesia checkout: choose one-time or auto-renewal, pay once with QRIS / card / virtual account through a Payment ID, and see IDR prices with PPN included.",
    steps: [
      {
        id: "idf-1",
        title: "Check the region and prices",
        do: "Open Settings → Workspace preferences: Region shows Indonesia. Then open the plan page.",
        expect: "Plan cards show Rp 54,000 / month for Personal and Rp 99,000 per seat for Pro, with 'includes PPN'. Yearly: Rp 395,000 and Rp 725,000 per seat. Enterprise still says Contact sales.",
        href: "/settings/workspace-preferences",
        refs: ["R-60", "R-61", "UX-25"],
        check: (_s, p) => p.startsWith("/plans") || p.startsWith("/settings/billing/change-plan"),
      },
      {
        id: "idf-2",
        title: "Choose 'Pay once' for Personal Monthly",
        do: "Upgrade to Personal → the 'How do you want to pay?' step appears → pick 'Pay once' → Continue.",
        expect: "The one-time checkout drawer opens with three methods: QRIS, Card (with 'Save this card for future bills') and Virtual Account (BRI, BCA, CIMB, Mandiri, Permata). It says the plan does not renew automatically and a bill comes 7 days before expiry.",
        href: "/plans",
        refs: ["M-10", "M-11", "R-61", "R-62"],
        check: (s) => (s.bills ?? []).length > 0,
      },
      {
        id: "idf-3",
        title: "Generate a Payment ID with QRIS",
        do: "Pick QRIS → Continue to payment.",
        expect: "A payment detail screen with a Payment ID (PAY-…), the QR code, the amount and a 2-hour countdown. Billing shows banner B-07 'A payment is still open' with Continue / Cancel.",
        refs: ["M-12", "R-63", "B-07"],
        check: (s) => has(s, "payment_pending"),
      },
      {
        id: "idf-4",
        title: "Confirm the payment",
        do: "Click 'I have paid' → Refresh status (or 'Simulate payment received' in the Prototype panel).",
        expect: "Status becomes Paid. Billing shows 'One-time · expires Oct 10, 2026', an invoice paid via QRIS, email N-32 (receipt). No card on file, no consent to recurring charges.",
        refs: ["M-13", "N-32", "R-64"],
        check: (s) => has(s, "bill_paid") && !s.subscription,
      },
      {
        id: "idf-5",
        title: "Jump to the bill day, then let it expire",
        do: "Prototype panel → 'Jump to bill day' (T-7) → then 'Jump to plan expiry' without paying.",
        expect: "At T-7 a bill is issued (banner B-06, email N-30, reminders N-30b at T-3 and T-1). At expiry the plan ends with no grace: account is Free, bill marked 'Expired unpaid', email N-31, banner B-08 'Buy a plan'.",
        refs: ["R-65", "N-30", "N-30b", "N-31", "B-06", "B-08"],
        check: (s) => has(s, "bill_expired"),
      },
      {
        id: "idf-6",
        title: "Switch region back to Australia",
        do: "Settings → Workspace preferences → Region: Australia → Save changes.",
        expect: "Prices return to AUD and the checkout goes straight to the card form (no 'Pay once' option). Any active plan would stay active across the change.",
        href: "/settings/workspace-preferences",
        refs: ["R-60", "R-66"],
        check: (s) => has(s, "region_changed") && s.region !== "ID",
      },
    ],
  },
  "id-onetime-card": {
    scenarioId: "id-onetime-card",
    goal: "A bill is waiting: pay it with a saved card, or convert a card payer to auto-renewal at the expiry date.",
    steps: [
      {
        id: "idc-1",
        title: "Read the bill",
        do: "Look at banner B-06 and Settings → Billing → Bills.",
        expect: "'Personal Monthly bill of Rp 54,000 is due by Sep 15, 2026 (5 days left)'. Status pill: 'One-time · expires Sep 15, 2026'. Buttons: Pay bill and Switch to auto-renewal (card payer). Invoice list shows the method column.",
        href: "/settings/billing",
        refs: ["B-06", "R-63", "R-64", "UX-26"],
        check: (_s, p) => p === "/settings/billing",
      },
      {
        id: "idc-2",
        title: "Pay with the saved card",
        do: "Pay bill → Card → 'Use saved card ending 4242' → Continue to payment → I have paid → Refresh.",
        expect: "Bill becomes Paid via card. The subscription line now reads 'expires Oct 15, 2026'. Still no auto-renewal; email N-32.",
        refs: ["M-11", "M-12", "M-13", "N-32"],
        check: (s) => has(s, "bill_paid"),
      },
      {
        id: "idc-3",
        title: "Turn on auto-renewal",
        do: "Reset the scenario. Banner → 'Switch to auto-renewal' → keep card 4242 → tick consent → Turn on.",
        expect: "The open bill is voided. A subscription starts with its first charge on Sep 15, 2026 (nothing charged today). Consent stored, email N-34, status 'Active · auto-renewal'. Jump to next renewal: Rp 54,000 charged, receipt N-03.",
        refs: ["M-14", "R-66", "N-34", "R-09"],
        note: "Reset the scenario first if you paid the bill in step 2.",
        check: (s) => has(s, "opt_in") && !!sub(s),
      },
      {
        id: "idc-4",
        title: "Let the bill expire instead",
        do: "Reset the scenario. Prototype panel → 'Jump to plan expiry' without paying.",
        expect: "Reminders N-30b at T-3 and T-1, then on Sep 15 the plan ends immediately (no 14-day grace). Bill 'Expired unpaid', account Free, email N-31, banner B-08.",
        refs: ["R-65", "N-30b", "N-31", "B-08"],
        note: "Optional. Reset the scenario first.",
        check: (s) => has(s, "bill_expired"),
      },
    ],
  },
  "id-onetime-qris": {
    scenarioId: "id-onetime-qris",
    goal: "Pro paid once by QRIS: no convert offer on the banner (phase 1), pay via virtual account, or expire and watch the workspace close with no grace.",
    steps: [
      {
        id: "idq-1",
        title: "No convert offer for non-card payers",
        do: "Look at the banner and the subscription card.",
        expect: "Banner B-06 shows only 'Pay bill' (2 days left). The 'Turn on auto-renewal' button is not on the subscription card, but the Payment methods section still offers it.",
        href: "/settings/billing",
        refs: ["R-66", "B-06"],
        check: (_s, p) => p === "/settings/billing",
      },
      {
        id: "idq-2",
        title: "Pay with a virtual account",
        do: "Pay bill → Virtual Account → BCA → Continue to payment.",
        expect: "Payment detail shows a BCA virtual account number with Copy, the exact amount (Rp 297,000 for 3 seats), the Payment ID and the 2-hour expiry. Bank-specific instructions are listed.",
        refs: ["M-12", "R-63"],
        check: (s) => has(s, "payment_pending"),
      },
      {
        id: "idq-3",
        title: "Cancel the Payment ID and pick another method",
        do: "Cancel this Payment ID → Pay bill again → QRIS → Continue → I have paid → Refresh.",
        expect: "Cancelling keeps the bill open. The second Payment ID succeeds; plan now runs to Oct 12, 2026 with 3 seats.",
        refs: ["B-07", "M-13", "N-32"],
        check: (s) => has(s, "bill_paid"),
      },
      {
        id: "idq-4",
        title: "Expire the workspace",
        do: "Reset the scenario. Prototype panel → 'Jump to plan expiry'.",
        expect: "On Sep 12 the workspace closes: members lose access, account is Free, bill expired, email N-31. Documents are kept.",
        refs: ["R-65", "N-31", "R-32"],
        note: "Reset the scenario first.",
        check: (s) => has(s, "bill_expired") && s.workspace.closed,
      },
    ],
  },
  "id-recurring": {
    scenarioId: "id-recurring",
    goal: "Indonesian auto-renewal behaves exactly like Global: same renewal engine, grace and retries, but in IDR.",
    steps: [
      {
        id: "idr-1",
        title: "Check the subscription card",
        do: "Open Settings → Billing.",
        expect: "'Active · auto-renewal', 'Renews on Oct 5, 2026 for Rp 54,000 on Visa ending 4242'. No Bills waiting. Payment methods show default and backup cards as usual.",
        href: "/settings/billing",
        refs: ["UX-01", "R-61"],
        check: (_s, p) => p === "/settings/billing",
      },
      {
        id: "idr-2",
        title: "Fail the renewal and see the grace period",
        do: "Prototype panel → 'Soft decline' → Jump to next renewal.",
        expect: "Banner B-01 with 14 days of access, retries on Day 3/7/14, email N-05 in IDR. Same behaviour as the Global past-due scenario.",
        refs: ["R-19", "B-01", "N-05"],
        check: (s) => sub(s)?.status === "past_due",
      },
      {
        id: "idr-3",
        title: "Upgrade to Pro",
        do: "Reset. Change plan → Upgrade to Pro → 2 seats → pay now.",
        expect: "Prorated charge in IDR for the rest of the period; renewal date unchanged. Same rules as Global.",
        href: "/settings/billing/change-plan",
        refs: ["R-24", "UX-08"],
        note: "Optional. Reset the scenario first.",
        check: (s) => sub(s)?.tier === "business",
      },
    ],
  },
};

export function guideFor(scenarioId: string): Guide {
  return GUIDES[scenarioId] ?? GUIDES.free;
}

export function stepDone(step: GuideStep, s: AppState, pathname: string): boolean {
  const manual = (s.ui.checkedSteps ?? []).includes(step.id);
  if (manual) return true;
  try {
    return step.check ? step.check(s, pathname) : false;
  } catch {
    return false;
  }
}
